using Domain.Entities.FinancialOperations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Domain.EntitiesConfigrations;

public class SourceEvidenceConfigration : IEntityTypeConfiguration<SourceEvidence>
{ public void Configure(EntityTypeBuilder<SourceEvidence> e) { e.ToTable("SourceEvidences"); e.Property(x => x.EvidenceType).IsRequired().HasMaxLength(64); e.Property(x => x.ExternalReference).IsRequired().HasMaxLength(128); e.Property(x => x.StorageLocator).IsRequired().HasMaxLength(1024); e.Property(x => x.ContentHash).IsRequired().HasMaxLength(128); e.Property(x => x.MetadataJson).IsRequired(); e.Property(x => x.ReceivedBy).IsRequired().HasMaxLength(450); e.Property(x => x.ReviewedBy).HasMaxLength(450); e.Property(x => x.ReviewComment).HasMaxLength(500); e.HasIndex(x => new { x.LegalEntityId, x.ContentHash }).IsUnique(); e.HasIndex(x => new { x.PlatformAccountId, x.ExternalReference }); e.HasOne(x => x.LegalEntity).WithMany().HasForeignKey(x => x.LegalEntityId).OnDelete(DeleteBehavior.Restrict); e.HasOne(x => x.PlatformAccount).WithMany().HasForeignKey(x => x.PlatformAccountId).OnDelete(DeleteBehavior.Restrict); e.HasOne(x => x.StoredFile).WithMany().HasForeignKey(x => x.StoredFileId).OnDelete(DeleteBehavior.Restrict); } }
public class PlatformSettlementConfigration : IEntityTypeConfiguration<PlatformSettlement>
{ public void Configure(EntityTypeBuilder<PlatformSettlement> e) { e.ToTable("PlatformSettlements", t => t.HasCheckConstraint("CK_PlatformSettlements_Amounts", "[GrossRevenue] >= 0 AND [CommissionAmount] >= 0 AND [NetSettlementAmount] >= 0")); e.Property(x => x.SettlementReference).IsRequired().HasMaxLength(128); e.Property(x => x.PostingProfileCode).IsRequired().HasMaxLength(64); e.Property(x => x.GrossRevenue).HasPrecision(18, 2); e.Property(x => x.CommissionAmount).HasPrecision(18, 2); e.Property(x => x.NetSettlementAmount).HasPrecision(18, 2); e.Property(x => x.CreatedBy).IsRequired().HasMaxLength(450); e.HasIndex(x => new { x.LegalEntityId, x.SettlementReference }).IsUnique(); e.HasOne(x => x.SourceEvidence).WithMany().HasForeignKey(x => x.SourceEvidenceId).OnDelete(DeleteBehavior.Restrict); e.HasOne(x => x.FinancialDocument).WithMany().HasForeignKey(x => x.FinancialDocumentId).OnDelete(DeleteBehavior.Restrict); } }
public class CustomerAccountConfigration : IEntityTypeConfiguration<CustomerAccount>
{ public void Configure(EntityTypeBuilder<CustomerAccount> e) { e.ToTable("CustomerAccounts"); e.Property(x => x.Code).IsRequired().HasMaxLength(64); e.Property(x => x.Name).IsRequired().HasMaxLength(200); e.Property(x => x.TaxRegistrationNumber).HasMaxLength(64); e.HasIndex(x => new { x.LegalEntityId, x.Code }).IsUnique(); e.HasOne(x => x.LegalEntity).WithMany().HasForeignKey(x => x.LegalEntityId).OnDelete(DeleteBehavior.Restrict); } }
public class CustomerInvoiceConfigration : IEntityTypeConfiguration<CustomerInvoice>
{ public void Configure(EntityTypeBuilder<CustomerInvoice> e) { e.ToTable("CustomerInvoices", t => t.HasCheckConstraint("CK_CustomerInvoices_Amounts", "[NetAmount] >= 0 AND [TaxAmount] >= 0 AND [GrossAmount] >= 0")); e.Property(x => x.InvoiceNumber).IsRequired().HasMaxLength(64); e.Property(x => x.CurrencyCode).IsRequired().HasMaxLength(3).IsFixedLength(); e.Property(x => x.PostingProfileCode).IsRequired().HasMaxLength(64); e.Property(x => x.NetAmount).HasPrecision(18, 2); e.Property(x => x.TaxAmount).HasPrecision(18, 2); e.Property(x => x.GrossAmount).HasPrecision(18, 2); e.Property(x => x.ExchangeRate).HasPrecision(19, 8); e.Property(x => x.CreatedBy).IsRequired().HasMaxLength(450); e.HasIndex(x => new { x.LegalEntityId, x.InvoiceNumber }).IsUnique(); e.HasOne(x => x.CustomerAccount).WithMany(x => x.Invoices).HasForeignKey(x => x.CustomerAccountId).OnDelete(DeleteBehavior.Restrict); e.HasOne(x => x.SourceEvidence).WithMany().HasForeignKey(x => x.SourceEvidenceId).OnDelete(DeleteBehavior.Restrict); e.HasOne(x => x.FinancialDocument).WithMany().HasForeignKey(x => x.FinancialDocumentId).OnDelete(DeleteBehavior.Restrict); } }
public class CustomerInvoiceLineConfigration : IEntityTypeConfiguration<CustomerInvoiceLine>
{ public void Configure(EntityTypeBuilder<CustomerInvoiceLine> e) { e.ToTable("CustomerInvoiceLines", t => t.HasCheckConstraint("CK_CustomerInvoiceLines_Quantity", "[Quantity] > 0 AND [UnitPrice] >= 0 AND [NetAmount] >= 0 AND [TaxAmount] >= 0")); e.Property(x => x.Description).IsRequired().HasMaxLength(500); e.Property(x => x.Quantity).HasPrecision(18, 4); e.Property(x => x.UnitPrice).HasPrecision(18, 4); e.Property(x => x.NetAmount).HasPrecision(18, 2); e.Property(x => x.TaxAmount).HasPrecision(18, 2); e.HasIndex(x => new { x.CustomerInvoiceId, x.LineNumber }).IsUnique(); e.HasOne(x => x.CustomerInvoice).WithMany(x => x.Lines).HasForeignKey(x => x.CustomerInvoiceId).OnDelete(DeleteBehavior.Cascade); e.HasOne(x => x.TaxCode).WithMany().HasForeignKey(x => x.TaxCodeId).OnDelete(DeleteBehavior.Restrict); } }
public class CustomerReceiptConfigration : IEntityTypeConfiguration<CustomerReceipt>
{ public void Configure(EntityTypeBuilder<CustomerReceipt> e) { e.ToTable("CustomerReceipts", t => t.HasCheckConstraint("CK_CustomerReceipts_Amount", "[Amount] > 0")); e.Property(x => x.ReceiptNumber).IsRequired().HasMaxLength(64); e.Property(x => x.ExternalReference).IsRequired().HasMaxLength(128); e.Property(x => x.CurrencyCode).IsRequired().HasMaxLength(3).IsFixedLength(); e.Property(x => x.PostingProfileCode).IsRequired().HasMaxLength(64); e.Property(x => x.Amount).HasPrecision(18, 2); e.Property(x => x.ExchangeRate).HasPrecision(19, 8); e.Property(x => x.CreatedBy).IsRequired().HasMaxLength(450); e.HasIndex(x => new { x.LegalEntityId, x.ReceiptNumber }).IsUnique(); e.HasIndex(x => new { x.LegalEntityId, x.ExternalReference }).IsUnique(); e.HasOne(x => x.CustomerAccount).WithMany().HasForeignKey(x => x.CustomerAccountId).OnDelete(DeleteBehavior.Restrict); e.HasOne(x => x.FinancialDocument).WithMany().HasForeignKey(x => x.FinancialDocumentId).OnDelete(DeleteBehavior.Restrict); } }
public class CustomerReceiptAllocationConfigration : IEntityTypeConfiguration<CustomerReceiptAllocation>
{ public void Configure(EntityTypeBuilder<CustomerReceiptAllocation> e) { e.ToTable("CustomerReceiptAllocations", t => t.HasCheckConstraint("CK_CustomerReceiptAllocations_Amount", "[Amount] > 0")); e.Property(x => x.Amount).HasPrecision(18, 2); e.Property(x => x.AllocatedBy).IsRequired().HasMaxLength(450); e.HasIndex(x => new { x.CustomerReceiptId, x.CustomerInvoiceId }).IsUnique(); e.HasOne(x => x.CustomerReceipt).WithMany(x => x.Allocations).HasForeignKey(x => x.CustomerReceiptId).OnDelete(DeleteBehavior.Restrict); e.HasOne(x => x.CustomerInvoice).WithMany().HasForeignKey(x => x.CustomerInvoiceId).OnDelete(DeleteBehavior.Restrict); } }
public class EmployeePayContractConfigration : IEntityTypeConfiguration<EmployeePayContract>
{ public void Configure(EntityTypeBuilder<EmployeePayContract> e) { e.ToTable("EmployeePayContracts", t => t.HasCheckConstraint("CK_EmployeePayContracts_Dates", "[EffectiveTo] IS NULL OR [EffectiveTo] >= [EffectiveFrom]")); e.Property(x => x.GrossSalary).HasPrecision(18, 2); e.Property(x => x.FixedDeduction).HasPrecision(18, 2); e.Property(x => x.CurrencyCode).IsRequired().HasMaxLength(3).IsFixedLength(); e.Property(x => x.CreatedBy).IsRequired().HasMaxLength(450); e.HasIndex(x => new { x.LegalEntityId, x.EmployeeIqamaNo, x.EffectiveFrom }).IsUnique(); } }
public class PayrollRunConfigration : IEntityTypeConfiguration<PayrollRun>
{ public void Configure(EntityTypeBuilder<PayrollRun> e) { e.ToTable("PayrollRuns", t => t.HasCheckConstraint("CK_PayrollRuns_Dates", "[PeriodEnd] >= [PeriodStart]")); e.Property(x => x.RunNumber).IsRequired().HasMaxLength(64); e.Property(x => x.CurrencyCode).IsRequired().HasMaxLength(3).IsFixedLength(); e.Property(x => x.PostingProfileCode).IsRequired().HasMaxLength(64); e.Property(x => x.GrossAmount).HasPrecision(18, 2); e.Property(x => x.DeductionAmount).HasPrecision(18, 2); e.Property(x => x.NetAmount).HasPrecision(18, 2); e.Property(x => x.CreatedBy).IsRequired().HasMaxLength(450); e.HasIndex(x => new { x.LegalEntityId, x.RunNumber }).IsUnique(); e.HasIndex(x => new { x.LegalEntityId, x.PeriodStart, x.PeriodEnd }).IsUnique(); e.HasOne(x => x.AccrualFinancialDocument).WithMany().HasForeignKey(x => x.AccrualFinancialDocumentId).OnDelete(DeleteBehavior.Restrict); e.HasOne(x => x.PaymentFinancialDocument).WithMany().HasForeignKey(x => x.PaymentFinancialDocumentId).OnDelete(DeleteBehavior.Restrict); } }
public class PayrollRunLineConfigration : IEntityTypeConfiguration<PayrollRunLine>
{ public void Configure(EntityTypeBuilder<PayrollRunLine> e) { e.ToTable("PayrollRunLines", t => t.HasCheckConstraint("CK_PayrollRunLines_Amounts", "[GrossAmount] >= 0 AND [DeductionAmount] >= 0 AND [NetAmount] >= 0")); e.Property(x => x.GrossAmount).HasPrecision(18, 2); e.Property(x => x.DeductionAmount).HasPrecision(18, 2); e.Property(x => x.NetAmount).HasPrecision(18, 2); e.HasIndex(x => new { x.PayrollRunId, x.EmployeeIqamaNo }).IsUnique(); e.HasOne(x => x.PayrollRun).WithMany(x => x.Lines).HasForeignKey(x => x.PayrollRunId).OnDelete(DeleteBehavior.Cascade); } }
public class SupplierAccountConfigration : IEntityTypeConfiguration<SupplierAccount>
{ public void Configure(EntityTypeBuilder<SupplierAccount> e) { e.ToTable("SupplierAccounts"); e.Property(x => x.Code).IsRequired().HasMaxLength(64); e.Property(x => x.Name).IsRequired().HasMaxLength(200); e.Property(x => x.TaxRegistrationNumber).HasMaxLength(64); e.HasIndex(x => new { x.LegalEntityId, x.Code }).IsUnique(); e.HasOne(x => x.LegalEntity).WithMany().HasForeignKey(x => x.LegalEntityId).OnDelete(DeleteBehavior.Restrict); } }
public class SupplierInvoiceConfigration : IEntityTypeConfiguration<SupplierInvoice>
{ public void Configure(EntityTypeBuilder<SupplierInvoice> e) { e.ToTable("SupplierInvoices", t => t.HasCheckConstraint("CK_SupplierInvoices_Amounts", "[NetAmount] >= 0 AND [TaxAmount] >= 0 AND [GrossAmount] >= 0")); e.Property(x => x.InvoiceNumber).IsRequired().HasMaxLength(64); e.Property(x => x.CurrencyCode).IsRequired().HasMaxLength(3).IsFixedLength(); e.Property(x => x.PostingProfileCode).IsRequired().HasMaxLength(64); e.Property(x => x.NetAmount).HasPrecision(18, 2); e.Property(x => x.TaxAmount).HasPrecision(18, 2); e.Property(x => x.GrossAmount).HasPrecision(18, 2); e.Property(x => x.ExchangeRate).HasPrecision(19, 8); e.Property(x => x.CreatedBy).IsRequired().HasMaxLength(450); e.HasIndex(x => new { x.LegalEntityId, x.InvoiceNumber }).IsUnique(); e.HasOne(x => x.SupplierAccount).WithMany().HasForeignKey(x => x.SupplierAccountId).OnDelete(DeleteBehavior.Restrict); e.HasOne(x => x.SourceEvidence).WithMany().HasForeignKey(x => x.SourceEvidenceId).OnDelete(DeleteBehavior.Restrict); e.HasOne(x => x.FinancialDocument).WithMany().HasForeignKey(x => x.FinancialDocumentId).OnDelete(DeleteBehavior.Restrict); } }
public class SupplierInvoiceLineConfigration : IEntityTypeConfiguration<SupplierInvoiceLine>
{ public void Configure(EntityTypeBuilder<SupplierInvoiceLine> e) { e.ToTable("SupplierInvoiceLines", t => t.HasCheckConstraint("CK_SupplierInvoiceLines_Quantity", "[Quantity] > 0 AND [UnitPrice] >= 0 AND [NetAmount] >= 0 AND [TaxAmount] >= 0")); e.Property(x => x.Description).IsRequired().HasMaxLength(500); e.Property(x => x.Quantity).HasPrecision(18, 4); e.Property(x => x.UnitPrice).HasPrecision(18, 4); e.Property(x => x.NetAmount).HasPrecision(18, 2); e.Property(x => x.TaxAmount).HasPrecision(18, 2); e.HasIndex(x => new { x.SupplierInvoiceId, x.LineNumber }).IsUnique(); e.HasOne(x => x.SupplierInvoice).WithMany(x => x.Lines).HasForeignKey(x => x.SupplierInvoiceId).OnDelete(DeleteBehavior.Cascade); e.HasOne(x => x.TaxCode).WithMany().HasForeignKey(x => x.TaxCodeId).OnDelete(DeleteBehavior.Restrict); } }
public class SupplierPaymentConfigration : IEntityTypeConfiguration<SupplierPayment>
{ public void Configure(EntityTypeBuilder<SupplierPayment> e) { e.ToTable("SupplierPayments", t => t.HasCheckConstraint("CK_SupplierPayments_Amount", "[Amount] > 0")); e.Property(x => x.PaymentNumber).IsRequired().HasMaxLength(64); e.Property(x => x.ExternalReference).IsRequired().HasMaxLength(128); e.Property(x => x.PostingProfileCode).IsRequired().HasMaxLength(64); e.Property(x => x.Amount).HasPrecision(18, 2); e.Property(x => x.CreatedBy).IsRequired().HasMaxLength(450); e.HasIndex(x => new { x.LegalEntityId, x.PaymentNumber }).IsUnique(); e.HasIndex(x => new { x.LegalEntityId, x.ExternalReference }).IsUnique(); e.HasOne(x => x.SupplierAccount).WithMany().HasForeignKey(x => x.SupplierAccountId).OnDelete(DeleteBehavior.Restrict); e.HasOne(x => x.FinancialDocument).WithMany().HasForeignKey(x => x.FinancialDocumentId).OnDelete(DeleteBehavior.Restrict); } }
public class SupplierPaymentAllocationConfigration : IEntityTypeConfiguration<SupplierPaymentAllocation>
{ public void Configure(EntityTypeBuilder<SupplierPaymentAllocation> e) { e.ToTable("SupplierPaymentAllocations", t => t.HasCheckConstraint("CK_SupplierPaymentAllocations_Amount", "[Amount] > 0")); e.Property(x => x.Amount).HasPrecision(18, 2); e.Property(x => x.AllocatedBy).IsRequired().HasMaxLength(450); e.HasIndex(x => new { x.SupplierPaymentId, x.SupplierInvoiceId }).IsUnique(); e.HasOne(x => x.SupplierPayment).WithMany(x => x.Allocations).HasForeignKey(x => x.SupplierPaymentId).OnDelete(DeleteBehavior.Restrict); e.HasOne(x => x.SupplierInvoice).WithMany().HasForeignKey(x => x.SupplierInvoiceId).OnDelete(DeleteBehavior.Restrict); } }
public class InventoryItemConfigration : IEntityTypeConfiguration<InventoryItem>
{ public void Configure(EntityTypeBuilder<InventoryItem> e) { e.ToTable("InventoryItems"); e.Property(x => x.Sku).IsRequired().HasMaxLength(64); e.Property(x => x.Name).IsRequired().HasMaxLength(200); e.Property(x => x.UnitOfMeasure).IsRequired().HasMaxLength(24); e.HasIndex(x => new { x.LegalEntityId, x.Sku }).IsUnique(); e.HasOne(x => x.LegalEntity).WithMany().HasForeignKey(x => x.LegalEntityId).OnDelete(DeleteBehavior.Restrict); } }
public class InventoryMovementConfigration : IEntityTypeConfiguration<InventoryMovement>
{ public void Configure(EntityTypeBuilder<InventoryMovement> e) { e.ToTable("InventoryMovements", t => t.HasCheckConstraint("CK_InventoryMovements_Amounts", "[Quantity] > 0 AND [UnitCost] >= 0")); e.Property(x => x.Reference).IsRequired().HasMaxLength(128); e.Property(x => x.FromBin).IsRequired().HasMaxLength(64); e.Property(x => x.ToBin).IsRequired().HasMaxLength(64); e.Property(x => x.PostingProfileCode).IsRequired().HasMaxLength(64); e.Property(x => x.Quantity).HasPrecision(18, 4); e.Property(x => x.UnitCost).HasPrecision(18, 4); e.Property(x => x.CreatedBy).IsRequired().HasMaxLength(450); e.HasIndex(x => new { x.LegalEntityId, x.Reference }).IsUnique(); e.HasOne(x => x.InventoryItem).WithMany().HasForeignKey(x => x.InventoryItemId).OnDelete(DeleteBehavior.Restrict); e.HasOne(x => x.FinancialDocument).WithMany().HasForeignKey(x => x.FinancialDocumentId).OnDelete(DeleteBehavior.Restrict); } }
public class ExpenseClaimConfigration : IEntityTypeConfiguration<ExpenseClaim>
{ public void Configure(EntityTypeBuilder<ExpenseClaim> e) { e.ToTable("ExpenseClaims", t => t.HasCheckConstraint("CK_ExpenseClaims_Amounts", "[NetAmount] >= 0 AND [TaxAmount] >= 0")); e.Property(x => x.ClaimNumber).IsRequired().HasMaxLength(64); e.Property(x => x.Description).IsRequired().HasMaxLength(500); e.Property(x => x.PostingProfileCode).IsRequired().HasMaxLength(64); e.Property(x => x.NetAmount).HasPrecision(18, 2); e.Property(x => x.TaxAmount).HasPrecision(18, 2); e.Property(x => x.CreatedBy).IsRequired().HasMaxLength(450); e.HasIndex(x => new { x.LegalEntityId, x.ClaimNumber }).IsUnique(); e.HasOne(x => x.SourceEvidence).WithMany().HasForeignKey(x => x.SourceEvidenceId).OnDelete(DeleteBehavior.Restrict); e.HasOne(x => x.TaxCode).WithMany().HasForeignKey(x => x.TaxCodeId).OnDelete(DeleteBehavior.Restrict); e.HasOne(x => x.FinancialDocument).WithMany().HasForeignKey(x => x.FinancialDocumentId).OnDelete(DeleteBehavior.Restrict); } }
public class BankAccountConfigration : IEntityTypeConfiguration<BankAccount>
{ public void Configure(EntityTypeBuilder<BankAccount> e) { e.ToTable("BankAccounts"); e.Property(x => x.Code).IsRequired().HasMaxLength(64); e.Property(x => x.Name).IsRequired().HasMaxLength(200); e.Property(x => x.CurrencyCode).IsRequired().HasMaxLength(3).IsFixedLength(); e.HasIndex(x => new { x.LegalEntityId, x.Code }).IsUnique(); e.HasOne(x => x.LegalEntity).WithMany().HasForeignKey(x => x.LegalEntityId).OnDelete(DeleteBehavior.Restrict); } }
public class BankStatementLineConfigration : IEntityTypeConfiguration<BankStatementLine>
{ public void Configure(EntityTypeBuilder<BankStatementLine> e) { e.ToTable("BankStatementLines"); e.Property(x => x.ExternalReference).IsRequired().HasMaxLength(128); e.Property(x => x.Description).IsRequired().HasMaxLength(500); e.Property(x => x.ReconciledBy).HasMaxLength(450); e.Property(x => x.Amount).HasPrecision(18, 2); e.HasIndex(x => new { x.BankAccountId, x.ExternalReference }).IsUnique(); e.HasOne(x => x.BankAccount).WithMany().HasForeignKey(x => x.BankAccountId).OnDelete(DeleteBehavior.Restrict); e.HasOne(x => x.MatchedFinancialDocument).WithMany().HasForeignKey(x => x.MatchedFinancialDocumentId).OnDelete(DeleteBehavior.Restrict); } }
public class TaxCodeConfigration : IEntityTypeConfiguration<TaxCode>
{ public void Configure(EntityTypeBuilder<TaxCode> e) { e.ToTable("TaxCodes", t => t.HasCheckConstraint("CK_TaxCodes_Rate", "[Rate] >= 0 AND [Rate] <= 1")); e.Property(x => x.Code).IsRequired().HasMaxLength(32); e.Property(x => x.Name).IsRequired().HasMaxLength(100); e.Property(x => x.Rate).HasPrecision(9, 6); e.HasIndex(x => new { x.LegalEntityId, x.Code }).IsUnique(); e.HasOne(x => x.LegalEntity).WithMany().HasForeignKey(x => x.LegalEntityId).OnDelete(DeleteBehavior.Restrict); } }
public class TaxTransactionConfigration : IEntityTypeConfiguration<TaxTransaction>
{ public void Configure(EntityTypeBuilder<TaxTransaction> e) { e.ToTable("TaxTransactions"); e.Property(x => x.SourceReference).IsRequired().HasMaxLength(128); e.Property(x => x.NetAmount).HasPrecision(18, 2); e.Property(x => x.TaxAmount).HasPrecision(18, 2); e.HasIndex(x => new { x.LegalEntityId, x.TransactionDate, x.TaxReturnId }); e.HasOne(x => x.TaxCode).WithMany().HasForeignKey(x => x.TaxCodeId).OnDelete(DeleteBehavior.Restrict); e.HasOne(x => x.FinancialDocument).WithMany().HasForeignKey(x => x.FinancialDocumentId).OnDelete(DeleteBehavior.Restrict); e.HasOne(x => x.TaxReturn).WithMany(x => x.TaxTransactions).HasForeignKey(x => x.TaxReturnId).OnDelete(DeleteBehavior.Restrict); } }
public class TaxReturnConfigration : IEntityTypeConfiguration<TaxReturn>
{ public void Configure(EntityTypeBuilder<TaxReturn> e) { e.ToTable("TaxReturns", t => t.HasCheckConstraint("CK_TaxReturns_Dates", "[PeriodEnd] >= [PeriodStart]")); e.Property(x => x.OutputTaxAmount).HasPrecision(18, 2); e.Property(x => x.InputTaxAmount).HasPrecision(18, 2); e.Property(x => x.NetTaxPayableAmount).HasPrecision(18, 2); e.Property(x => x.SubmissionReference).HasMaxLength(128); e.Property(x => x.CreatedBy).IsRequired().HasMaxLength(450); e.Property(x => x.SubmittedBy).HasMaxLength(450); e.HasIndex(x => new { x.LegalEntityId, x.PeriodStart, x.PeriodEnd }).IsUnique(); e.HasOne(x => x.LegalEntity).WithMany().HasForeignKey(x => x.LegalEntityId).OnDelete(DeleteBehavior.Restrict); } }
public class FixedAssetConfigration : IEntityTypeConfiguration<FixedAsset>
{ public void Configure(EntityTypeBuilder<FixedAsset> e) { e.ToTable("FixedAssets", t => t.HasCheckConstraint("CK_FixedAssets_Values", "[AcquisitionCost] >= 0 AND [ResidualValue] >= 0 AND [ResidualValue] <= [AcquisitionCost] AND [UsefulLifeMonths] > 0")); e.Property(x => x.AssetNumber).IsRequired().HasMaxLength(64); e.Property(x => x.Description).IsRequired().HasMaxLength(500); e.Property(x => x.AcquisitionCost).HasPrecision(18, 2); e.Property(x => x.ResidualValue).HasPrecision(18, 2); e.HasIndex(x => new { x.LegalEntityId, x.AssetNumber }).IsUnique(); e.HasOne(x => x.LegalEntity).WithMany().HasForeignKey(x => x.LegalEntityId).OnDelete(DeleteBehavior.Restrict); } }
public class BudgetConfigration : IEntityTypeConfiguration<Budget>
{ public void Configure(EntityTypeBuilder<Budget> e) { e.ToTable("Budgets", t => t.HasCheckConstraint("CK_Budgets_Dates", "[EndDate] >= [StartDate]")); e.Property(x => x.Name).IsRequired().HasMaxLength(128); e.Property(x => x.CreatedBy).IsRequired().HasMaxLength(450); e.HasIndex(x => new { x.LegalEntityId, x.Name }).IsUnique(); e.HasOne(x => x.LegalEntity).WithMany().HasForeignKey(x => x.LegalEntityId).OnDelete(DeleteBehavior.Restrict); } }
public class BudgetLineConfigration : IEntityTypeConfiguration<BudgetLine>
{ public void Configure(EntityTypeBuilder<BudgetLine> e) { e.ToTable("BudgetLines"); e.Property(x => x.Amount).HasPrecision(18, 2); e.HasIndex(x => new { x.BudgetId, x.AccountId, x.FinancialDimensionValueId }).IsUnique(); e.HasOne(x => x.Budget).WithMany(x => x.Lines).HasForeignKey(x => x.BudgetId).OnDelete(DeleteBehavior.Cascade); e.HasOne(x => x.Account).WithMany().HasForeignKey(x => x.AccountId).OnDelete(DeleteBehavior.Restrict); e.HasOne(x => x.FinancialDimensionValue).WithMany().HasForeignKey(x => x.FinancialDimensionValueId).OnDelete(DeleteBehavior.Restrict); } }
