using Application.Abstraction;
using Application.Contracts.Common;
using Application.Contracts.FinancialOperations;

namespace Application.Service.FinancialOperations;

public interface IFinancialOperationsService
{
    Task<Result<PagedResponse<MasterRecordResponse>>> GetCustomerAccountsAsync(PaginationRequest pagination, MasterRecordListFilter filter, string actorId, CancellationToken ct = default);
    Task<Result<MasterRecordResponse>> GetCustomerAccountAsync(Guid id, string actorId, CancellationToken ct = default);
    Task<Result<PagedResponse<FinancialOperationResponse>>> GetCustomerInvoicesAsync(PaginationRequest pagination, CustomerInvoiceListFilter filter, string actorId, CancellationToken ct = default);
    Task<Result<FinancialOperationResponse>> GetCustomerInvoiceAsync(Guid id, string actorId, CancellationToken ct = default);
    Task<Result<PagedResponse<FinancialOperationResponse>>> GetCustomerReceiptsAsync(PaginationRequest pagination, CustomerReceiptListFilter filter, string actorId, CancellationToken ct = default);
    Task<Result<FinancialOperationResponse>> GetCustomerReceiptAsync(Guid id, string actorId, CancellationToken ct = default);
    Task<Result<PagedResponse<FinancialOperationResponse>>> GetPlatformSettlementsAsync(PaginationRequest pagination, PlatformSettlementListFilter filter, string actorId, CancellationToken ct = default);
    Task<Result<FinancialOperationResponse>> GetPlatformSettlementAsync(Guid id, string actorId, CancellationToken ct = default);
    Task<Result<PagedResponse<MasterRecordResponse>>> GetSupplierAccountsAsync(PaginationRequest pagination, MasterRecordListFilter filter, string actorId, CancellationToken ct = default);
    Task<Result<MasterRecordResponse>> GetSupplierAccountAsync(Guid id, string actorId, CancellationToken ct = default);
    Task<Result<PagedResponse<FinancialOperationResponse>>> GetSupplierInvoicesAsync(PaginationRequest pagination, SupplierInvoiceListFilter filter, string actorId, CancellationToken ct = default);
    Task<Result<FinancialOperationResponse>> GetSupplierInvoiceAsync(Guid id, string actorId, CancellationToken ct = default);
    Task<Result<PagedResponse<FinancialOperationResponse>>> GetSupplierPaymentsAsync(PaginationRequest pagination, SupplierPaymentListFilter filter, string actorId, CancellationToken ct = default);
    Task<Result<FinancialOperationResponse>> GetSupplierPaymentAsync(Guid id, string actorId, CancellationToken ct = default);
    Task<Result<PagedResponse<SourceEvidenceResponse>>> GetSourceEvidenceAsync(PaginationRequest pagination, SourceEvidenceListFilter filter, string actorId, CancellationToken ct = default);
    Task<Result<SourceEvidenceResponse>> GetSourceEvidenceAsync(Guid id, string actorId, CancellationToken ct = default);
    Task<Result<PagedResponse<FinancialOperationResponse>>> GetExpenseClaimsAsync(PaginationRequest pagination, ExpenseClaimListFilter filter, string actorId, CancellationToken ct = default);
    Task<Result<FinancialOperationResponse>> GetExpenseClaimAsync(Guid id, string actorId, CancellationToken ct = default);
    Task<Result<PagedResponse<MasterRecordResponse>>> GetInventoryItemsAsync(PaginationRequest pagination, MasterRecordListFilter filter, string actorId, CancellationToken ct = default);
    Task<Result<MasterRecordResponse>> GetInventoryItemAsync(Guid id, string actorId, CancellationToken ct = default);
    Task<Result<PagedResponse<FinancialOperationResponse>>> GetInventoryMovementsAsync(PaginationRequest pagination, InventoryMovementListFilter filter, string actorId, CancellationToken ct = default);
    Task<Result<FinancialOperationResponse>> GetInventoryMovementAsync(Guid id, string actorId, CancellationToken ct = default);
    Task<Result<PagedResponse<InventoryStockBalanceResponse>>> GetInventoryStockBalancesAsync(PaginationRequest pagination, InventoryStockBalanceListFilter filter, string actorId, CancellationToken ct = default);
    Task<Result<PagedResponse<MasterRecordResponse>>> GetBankAccountsAsync(PaginationRequest pagination, MasterRecordListFilter filter, string actorId, CancellationToken ct = default);
    Task<Result<MasterRecordResponse>> GetBankAccountAsync(Guid id, string actorId, CancellationToken ct = default);
    Task<Result<PagedResponse<FinancialOperationResponse>>> GetBankStatementLinesAsync(PaginationRequest pagination, BankStatementLineListFilter filter, string actorId, CancellationToken ct = default);
    Task<Result<FinancialOperationResponse>> GetBankStatementLineAsync(Guid id, string actorId, CancellationToken ct = default);
    Task<Result<PagedResponse<TaxCodeResponse>>> GetTaxCodesAsync(PaginationRequest pagination, TaxCodeListFilter filter, string actorId, CancellationToken ct = default);
    Task<Result<TaxCodeResponse>> GetTaxCodeAsync(int id, string actorId, CancellationToken ct = default);
    Task<Result<PagedResponse<TaxReturnResponse>>> GetTaxReturnsAsync(PaginationRequest pagination, TaxReturnListFilter filter, string actorId, CancellationToken ct = default);
    Task<Result<TaxReturnResponse>> GetTaxReturnAsync(Guid id, string actorId, CancellationToken ct = default);
    Task<Result<PagedResponse<FixedAssetResponse>>> GetFixedAssetsAsync(PaginationRequest pagination, FixedAssetListFilter filter, string actorId, CancellationToken ct = default);
    Task<Result<FixedAssetResponse>> GetFixedAssetAsync(Guid id, string actorId, CancellationToken ct = default);
    Task<Result<PagedResponse<BudgetResponse>>> GetBudgetsAsync(PaginationRequest pagination, BudgetListFilter filter, string actorId, CancellationToken ct = default);
    Task<Result<BudgetResponse>> GetBudgetAsync(Guid id, string actorId, CancellationToken ct = default);
    Task<Result<SourceEvidenceResponse>> CreateSourceEvidenceAsync(CreateSourceEvidenceRequest request, string actorId, CancellationToken ct = default);
    Task<Result<SourceEvidenceResponse>> CreatePrivateSourceEvidenceAsync(CreatePrivateSourceEvidenceRequest request, string actorId, CancellationToken ct = default);
    Task<Result<SourceEvidenceResponse>> ReviewSourceEvidenceAsync(Guid id, ReviewSourceEvidenceRequest request, string actorId, CancellationToken ct = default);
    Task<Result<FinancialOperationResponse>> RecordPlatformSettlementAsync(RecordPlatformSettlementRequest request, string actorId, CancellationToken ct = default);
    Task<Result<MasterRecordResponse>> CreateCustomerAccountAsync(CreateCustomerAccountRequest request, string actorId, CancellationToken ct = default);
    Task<Result<FinancialOperationResponse>> CreateCustomerInvoiceAsync(CreateCustomerInvoiceRequest request, string actorId, CancellationToken ct = default);
    Task<Result<FinancialOperationResponse>> IssueCustomerInvoiceAsync(Guid id, IssueCustomerInvoiceRequest request, string actorId, CancellationToken ct = default);
    Task<Result<FinancialOperationResponse>> RecordCustomerReceiptAsync(RecordCustomerReceiptRequest request, string actorId, CancellationToken ct = default);
    Task<Result> AllocateCustomerReceiptAsync(Guid receiptId, AllocateCustomerReceiptRequest request, string actorId, CancellationToken ct = default);
    Task<Result<MasterRecordResponse>> CreateEmployeePayContractAsync(CreateEmployeePayContractRequest request, string actorId, CancellationToken ct = default);
    Task<Result<PayrollRunResponse>> CreatePayrollRunAsync(CreatePayrollRunRequest request, string actorId, CancellationToken ct = default);
    Task<Result<PayrollRunResponse>> PreparePayrollRunAsync(Guid id, PreparePayrollRunRequest request, string actorId, CancellationToken ct = default);
    Task<Result<PayrollRunResponse>> PayPayrollRunAsync(Guid id, PayPayrollRunRequest request, string actorId, CancellationToken ct = default);
    Task<Result<MasterRecordResponse>> CreateSupplierAccountAsync(CreateSupplierAccountRequest request, string actorId, CancellationToken ct = default);
    Task<Result<FinancialOperationResponse>> CreateSupplierInvoiceAsync(CreateSupplierInvoiceRequest request, string actorId, CancellationToken ct = default);
    Task<Result<FinancialOperationResponse>> RecordSupplierInvoiceAsync(Guid id, RecordSupplierInvoiceRequest request, string actorId, CancellationToken ct = default);
    Task<Result<FinancialOperationResponse>> RecordSupplierPaymentAsync(RecordSupplierPaymentRequest request, string actorId, CancellationToken ct = default);
    Task<Result> AllocateSupplierPaymentAsync(Guid paymentId, AllocateSupplierPaymentRequest request, string actorId, CancellationToken ct = default);
    Task<Result<MasterRecordResponse>> CreateInventoryItemAsync(CreateInventoryItemRequest request, string actorId, CancellationToken ct = default);
    Task<Result<FinancialOperationResponse>> RecordInventoryMovementAsync(RecordInventoryMovementRequest request, string actorId, CancellationToken ct = default);
    Task<Result<FinancialOperationResponse>> CreateExpenseClaimAsync(CreateExpenseClaimRequest request, string actorId, CancellationToken ct = default);
    Task<Result<MasterRecordResponse>> CreateBankAccountAsync(CreateBankAccountRequest request, string actorId, CancellationToken ct = default);
    Task<Result<FinancialOperationResponse>> RecordBankStatementLineAsync(RecordBankStatementLineRequest request, string actorId, CancellationToken ct = default);
    Task<Result<FinancialOperationResponse>> ReconcileBankStatementLineAsync(Guid id, ReconcileBankStatementLineRequest request, string actorId, CancellationToken ct = default);
    Task<Result<TaxCodeResponse>> CreateTaxCodeAsync(CreateTaxCodeRequest request, string actorId, CancellationToken ct = default);
    Task<Result<TaxReturnResponse>> PrepareTaxReturnAsync(PrepareTaxReturnRequest request, string actorId, CancellationToken ct = default);
    Task<Result<TaxReturnResponse>> SubmitTaxReturnAsync(Guid id, SubmitTaxReturnRequest request, string actorId, CancellationToken ct = default);
    Task<Result<FixedAssetResponse>> CreateFixedAssetAsync(CreateFixedAssetRequest request, string actorId, CancellationToken ct = default);
    Task<Result<BudgetResponse>> CreateBudgetAsync(CreateBudgetRequest request, string actorId, CancellationToken ct = default);
}
