// <auto-generated />
using System;
using Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Domain.Migrations
{
    [DbContext(typeof(ApplicationDbcontext))]
    [Migration("20260409122104_addingupdatedattoemployees")]
    partial class addingupdatedattoemployees
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "77B96CED-F902-47EF-AE95-ABBE14A8CA22",
                            ConcurrencyStamp = "B0AD2D39-253B-42E4-88F2-F6FE83A614A8",
                            IsDefault = false,
                            IsDeleted = false,
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "77B96C5D-F502-47TF-EE95-ABVN14A3CA22",
                            ConcurrencyStamp = "A7B75EE9-DB35-480D-9F9F-18D2E499B004",
                            IsDefault = true,
                            IsDeleted = false,
                            Name = "Member",
                            NormalizedName = "MEMBER"
                        },
                        new
                        {
                            Id = "17B96C5D-F502-47TF-EE95-ABVN14A3CA22",
                            ConcurrencyStamp = "17B75EE9-DB35-480D-9F9F-18D2E499B004",
                            IsDefault = false,
                            IsDeleted = false,
                            Name = "Master",
                            NormalizedName = "MASTER"
                        });
                });

            modelBuilder.Entity("Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDisable")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "59724D2D-E2B5-4C67-AB6F-D93478347B03",
                            AccessFailedCount = 0,
                            Address = "",
                            ConcurrencyStamp = "B4555410-F5B0-45B1-B963-1B2351A0723C",
                            EmailConfirmed = true,
                            FullName = "",
                            IsDisable = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEKsFIretIX6QKFrgMB27GBFARBhK4OxtOLzvqHaI0guCe5N78ihbfbXYGe2uig2EUw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9FABB58491024B7BB140E4D6658B5BDA",
                            TwoFactorEnabled = false,
                            UserName = "Admin"
                        },
                        new
                        {
                            Id = "59726D2D-E2B5-4C67-AB6F-D93478317B03",
                            AccessFailedCount = 0,
                            Address = "",
                            ConcurrencyStamp = "B4555410-F5B0-45B1-B963-1B2351A0723C",
                            EmailConfirmed = true,
                            FullName = "",
                            IsDisable = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "MASTER",
                            PasswordHash = "AQAAAAIAAYagAAAAEOTcsCOs75bXyb9izxcow+8dUa0gCN0gXV2V/j9GrwxkIJHQRp6z4hMe3/qOABEkhQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9FABB58491024B7BB140E4D6658B5BDA",
                            TwoFactorEnabled = false,
                            UserName = "Master"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("From")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly?>("To")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Domain.Entities.DailyReportLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSent")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("ReportDate")
                        .HasColumnType("date");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DailyReportLogs");
                });

            modelBuilder.Entity("Domain.Entities.DeletedEmployees", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcountStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HousingId")
                        .HasColumnType("int");

                    b.Property<string>("IBAN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("INKSA")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("IqamaEndH")
                        .HasColumnType("date");

                    b.Property<DateOnly>("IqamaEndM")
                        .HasColumnType("date");

                    b.Property<long>("IqamaNo")
                        .HasColumnType("bigint");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("PassportEnd")
                        .HasColumnType("date");

                    b.Property<string>("PassportNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sponsor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TshirtSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("int");

                    b.Property<string>("WorkingId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DeletedEmployees");
                });

            modelBuilder.Entity("Domain.Entities.EmployeeDocuments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdditionImage1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdditionImage2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdditionImage3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("EmployeeIqamaNo")
                        .HasColumnType("bigint");

                    b.Property<string>("IqamaImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassportImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkPermitImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeIqamaNo")
                        .IsUnique();

                    b.ToTable("EmployeeDocuments");
                });

            modelBuilder.Entity("Domain.Entities.Employees", b =>
                {
                    b.Property<long>("IqamaNo")
                        .HasColumnType("bigint");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HousingId")
                        .HasColumnType("int");

                    b.Property<string>("IBAN")
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.Property<bool>("INKSA")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("IqamaEndH")
                        .HasColumnType("date");

                    b.Property<DateOnly>("IqamaEndM")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmployee")
                        .HasColumnType("bit");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("NameAR")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameEN")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("PassportEnd")
                        .HasColumnType("date");

                    b.Property<string>("PassportNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Sponsor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("sponsorNo")
                        .HasColumnType("bigint");

                    b.HasKey("IqamaNo");

                    b.HasIndex("HousingId");

                    b.HasIndex("NameAR");

                    b.HasIndex("NameEN");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Employees_Status");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Domain.Entities.EscapedEmployeeDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivePath")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfOutage")
                        .HasColumnType("datetime2");

                    b.Property<long>("EmployeeIqamaNo")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("EscapedAt")
                        .HasColumnType("date");

                    b.Property<bool?>("IsOutage")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsReported")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutageVisaNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RemovalDeadline")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReportedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TenDayNotificationSent")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("TenDayNotificationSentAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeIqamaNo")
                        .IsUnique();

                    b.ToTable("EscapedEmployeeDetails");
                });

            modelBuilder.Entity("Domain.Entities.Housing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<long?>("ManagerIqamaNo")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Housings");
                });

            modelBuilder.Entity("Domain.Entities.HungerDisability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcceptedDailyOrders")
                        .HasColumnType("int");

                    b.Property<int>("ActualRiderId")
                        .HasColumnType("int");

                    b.Property<string>("ActualWorkingId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Days")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ShiftDate")
                        .HasColumnType("date");

                    b.Property<int?>("SubstituteRiderId")
                        .HasColumnType("int");

                    b.Property<string>("SubstituteWorkingId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ActualWorkingId")
                        .HasDatabaseName("IX_HungerDisability_ActualWorkingId");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("IX_HungerDisability_CompanyId");

                    b.HasIndex("ShiftDate")
                        .HasDatabaseName("IX_HungerDisability_ShiftDate");

                    b.HasIndex("SubstituteRiderId")
                        .HasDatabaseName("IX_HungerDisability_SubstituteRiderId");

                    b.HasIndex("ActualRiderId", "ShiftDate")
                        .IsUnique()
                        .HasDatabaseName("IX_HungerDisability_ActualRider_ShiftDate");

                    b.ToTable("HungerDisabilities", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Keeta.Company2ValidationConfig", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("AllowedMissingDays28")
                        .HasColumnType("int");

                    b.Property<int>("AllowedMissingDays29")
                        .HasColumnType("int");

                    b.Property<int>("AllowedMissingDays30")
                        .HasColumnType("int");

                    b.Property<int>("AllowedMissingDays31")
                        .HasColumnType("int");

                    b.Property<string>("CriticalDaysOfMonth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FirstCriticalDaysCount")
                        .HasColumnType("int");

                    b.Property<int>("FullMonthTargetOrders")
                        .HasColumnType("int");

                    b.Property<bool>("IsFridayCritical")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSaturdayCritical")
                        .HasColumnType("bit");

                    b.Property<bool>("IsThursdayCritical")
                        .HasColumnType("bit");

                    b.Property<int>("LastCriticalDaysCount")
                        .HasColumnType("int");

                    b.Property<int>("MaxStartDayForExistingRiders")
                        .HasColumnType("int");

                    b.Property<float>("MinWorkingHoursPerDay")
                        .HasColumnType("real");

                    b.Property<float>("TargetHoursPerDay")
                        .HasColumnType("real");

                    b.Property<int>("TargetOrdersPerDay")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Company2ValidationConfig", null, t =>
                        {
                            t.HasCheckConstraint("CK_Company2ValidationConfig_Singleton", "[Id] = 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllowedMissingDays28 = 3,
                            AllowedMissingDays29 = 3,
                            AllowedMissingDays30 = 4,
                            AllowedMissingDays31 = 5,
                            CriticalDaysOfMonth = "",
                            FirstCriticalDaysCount = 3,
                            FullMonthTargetOrders = 300,
                            IsFridayCritical = false,
                            IsSaturdayCritical = false,
                            IsThursdayCritical = false,
                            LastCriticalDaysCount = 4,
                            MaxStartDayForExistingRiders = 5,
                            MinWorkingHoursPerDay = 10f,
                            TargetHoursPerDay = 10.5f,
                            TargetOrdersPerDay = 12,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("Domain.Entities.KetaFreeLancer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RiderId")
                        .HasColumnType("int");

                    b.Property<int>("TotalOrders")
                        .HasColumnType("int");

                    b.Property<string>("WorkingId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RiderId");

                    b.ToTable("KetaFreeLancers");
                });

            modelBuilder.Entity("Domain.Entities.RiderCompanyHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RiderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("RiderCompanyHistory");
                });

            modelBuilder.Entity("Domain.Entities.RiderDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("EmployeeIqamaNo")
                        .HasColumnType("bigint");

                    b.Property<string>("LicenseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TshirtSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("WorkingId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("EmployeeIqamaNo")
                        .IsUnique();

                    b.HasIndex("VehicleNumber")
                        .IsUnique()
                        .HasFilter("[VehicleNumber] IS NOT NULL");

                    b.HasIndex("WorkingId");

                    b.ToTable("RiderDetails");
                });

            modelBuilder.Entity("Domain.Entities.RiderMonthlyValidity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("EmployeeIqamaNo")
                        .HasColumnType("bigint");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TotalOrders")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeIqamaNo");

                    b.ToTable("RiderMonthlyValidities");
                });

            modelBuilder.Entity("Domain.Entities.RiderShift", b =>
                {
                    b.Property<int>("RiderId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ShiftDate")
                        .HasColumnType("date");

                    b.Property<string>("WorkingId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AcceptedDailyOrders")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HousingId")
                        .HasColumnType("int");

                    b.Property<int>("RealRejectedDailyOrders")
                        .HasColumnType("int");

                    b.Property<int>("RejectedDailyOrders")
                        .HasColumnType("int");

                    b.Property<string>("ShiftStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("StackedDeliveries")
                        .HasColumnType("int");

                    b.Property<float>("WorkingHours")
                        .HasColumnType("real");

                    b.HasKey("RiderId", "ShiftDate", "WorkingId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("HousingId");

                    b.HasIndex("RiderId");

                    b.HasIndex("ShiftDate");

                    b.HasIndex("ShiftStatus");

                    b.HasIndex("WorkingId");

                    b.ToTable("RiderShifts");
                });

            modelBuilder.Entity("Domain.Entities.RiderShiftSubstitution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActualRiderId")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<string>("ActualRiderWorkingId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long?>("OriginalRiderIqamaNo")
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubstituteRiderId")
                        .HasColumnType("int");

                    b.Property<string>("SubstituteWorkingId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ActualRiderId");

                    b.HasIndex("SubstituteRiderId");

                    b.HasIndex("ActualRiderWorkingId", "IsActive");

                    b.HasIndex("SubstituteWorkingId", "IsActive");

                    b.ToTable("RiderShiftSubstitutions");
                });

            modelBuilder.Entity("Domain.Entities.RiderVehicleStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long?>("EmployeeIqamaNo")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Permission")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("PermissionEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PermissionStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusType")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("VehicleNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("EmployeeIqamaNo", "IsActive");

                    b.HasIndex("VehicleNumber", "IsActive");

                    b.HasIndex("VehicleNumber", "IsActive", "PermissionEndDate")
                        .HasFilter("[PermissionEndDate] IS NOT NULL");

                    b.HasIndex("VehicleNumber", "IsActive", "StatusType");

                    b.ToTable("RiderVehicleStatus");
                });

            modelBuilder.Entity("Domain.Entities.RiderWorkingIdHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RiderIqamaNo")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("WorkingId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("RiderIqamaNo");

                    b.HasIndex("WorkingId");

                    b.HasIndex("RiderIqamaNo", "IsActive");

                    b.HasIndex("WorkingId", "IsActive");

                    b.ToTable("RiderWorkingIdHistories");
                });

            modelBuilder.Entity("Domain.Entities.Spare.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProcessedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(38, 0)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceNumber");

                    b.HasIndex("ProcessedAt");

                    b.HasIndex("SupplierId");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("Domain.Entities.Spare.BillItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BillId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemType")
                        .HasColumnType("int");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(38, 0)");

                    b.Property<decimal?>("NewAveragePrice")
                        .HasColumnType("decimal(38, 0)");

                    b.Property<decimal>("OldPrice")
                        .HasColumnType("decimal(38, 0)");

                    b.Property<bool>("PriceChanged")
                        .HasColumnType("bit");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(38, 0)");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.ToTable("BillItems");
                });

            modelBuilder.Entity("Domain.Entities.Spare.Return", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProcessedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReturnNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(38, 0)");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("Returns");
                });

            modelBuilder.Entity("Domain.Entities.Spare.ReturnItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemType")
                        .HasColumnType("int");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(38, 0)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ReturnId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(38, 0)");

                    b.HasKey("Id");

                    b.HasIndex("ReturnId");

                    b.ToTable("ReturnItems");
                });

            modelBuilder.Entity("Domain.Entities.Spare.RiderAccessory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(38, 0)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Location");

                    b.HasIndex("Name");

                    b.ToTable("RiderAccessories");
                });

            modelBuilder.Entity("Domain.Entities.Spare.RiderAccessoryUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Cost")
                        .HasColumnType("decimal(38, 0)");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RiderAccessoryId")
                        .HasColumnType("int");

                    b.Property<int>("RiderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IssuedAt");

                    b.HasIndex("RiderAccessoryId");

                    b.HasIndex("RiderId");

                    b.ToTable("RiderAccessoryUsages");
                });

            modelBuilder.Entity("Domain.Entities.Spare.SparePart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(38, 0)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Location");

                    b.HasIndex("Name");

                    b.ToTable("SpareParts");
                });

            modelBuilder.Entity("Domain.Entities.Spare.SparePartUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Cost")
                        .HasColumnType("decimal(38, 0)");

                    b.Property<int>("QuantityUsed")
                        .HasColumnType("int");

                    b.Property<int>("SparePartId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UsedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VehicleNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("SparePartId");

                    b.HasIndex("UsedAt");

                    b.HasIndex("VehicleNumber");

                    b.ToTable("SparePartUsages");
                });

            modelBuilder.Entity("Domain.Entities.Spare.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TaxNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("Domain.Entities.Spare.Transfer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FromLocation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("HousingId")
                        .HasColumnType("int");

                    b.Property<string>("ToLocation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("TransferredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransferredBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("HousingId");

                    b.HasIndex("TransferredAt");

                    b.ToTable("Transfers");
                });

            modelBuilder.Entity("Domain.Entities.Spare.TransferItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ItemType")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("TransferId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TransferId", "ItemType");

                    b.ToTable("TransferItems");
                });

            modelBuilder.Entity("Domain.Entities.TempEmployeeStatusChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("AdminNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("EmployeeIqamaNo")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("bit");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Resolution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResolvedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeIqamaNo");

                    b.HasIndex("IsResolved");

                    b.HasIndex("RequestedAt");

                    b.ToTable("TempEmployeeStatusChanges");
                });

            modelBuilder.Entity("Domain.Entities.TempEmployeeUpdate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("IqamaNo")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsNewEmployee")
                        .HasColumnType("bit");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("bit");

                    b.Property<string>("NewCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("NewDateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("NewIBAN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("NewINKSA")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("NewIqamaEndH")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NewIqamaEndM")
                        .HasColumnType("date");

                    b.Property<string>("NewJobTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewNameAR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewNameEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("NewPassportEnd")
                        .HasColumnType("date");

                    b.Property<string>("NewPassportNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewSponsor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("NewSponsorNo")
                        .HasColumnType("bigint");

                    b.Property<string>("NewStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("OldDateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("OldIBAN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("OldINKSA")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("OldIqamaEndH")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("OldIqamaEndM")
                        .HasColumnType("date");

                    b.Property<string>("OldJobTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldNameAR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldNameEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("OldPassportEnd")
                        .HasColumnType("date");

                    b.Property<string>("OldPassportNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldSponsor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("OldSponsorNo")
                        .HasColumnType("bigint");

                    b.Property<string>("OldStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resolution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResolvedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UploadedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IqamaNo");

                    b.HasIndex("IsResolved");

                    b.HasIndex("UploadedAt");

                    b.ToTable("TempEmployeeUpdates");
                });

            modelBuilder.Entity("Domain.Entities.TempRiderShiftComparison", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int?>("HousingId")
                        .HasColumnType("int");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSubstitution")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("NewAcceptedDailyOrders")
                        .HasColumnType("int");

                    b.Property<int>("NewRealRejectedDailyOrders")
                        .HasColumnType("int");

                    b.Property<int>("NewRejectedDailyOrders")
                        .HasColumnType("int");

                    b.Property<string>("NewShiftStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NewStackedDeliveries")
                        .HasColumnType("int");

                    b.Property<float>("NewWorkingHours")
                        .HasColumnType("real");

                    b.Property<int?>("OldAcceptedDailyOrders")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OldCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OldRealRejectedDailyOrders")
                        .HasColumnType("int");

                    b.Property<int?>("OldRejectedDailyOrders")
                        .HasColumnType("int");

                    b.Property<string>("OldShiftStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("OldStackedDeliveries")
                        .HasColumnType("int");

                    b.Property<float?>("OldWorkingHours")
                        .HasColumnType("real");

                    b.Property<string>("OriginalRiderWorkingId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RiderId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ShiftDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WorkingId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("HousingId");

                    b.HasIndex("IsResolved");

                    b.HasIndex("IsSubstitution");

                    b.HasIndex("ShiftDate", "WorkingId");

                    b.HasIndex("RiderId", "WorkingId", "ShiftDate");

                    b.ToTable("TempRiderShiftComparisons");
                });

            modelBuilder.Entity("Domain.Entities.TempVehicleOperation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsResolved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Permission")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("PermissionEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("RequestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Resolution")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResolvedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long?>("RiderIqamaNo")
                        .HasColumnType("bigint");

                    b.Property<string>("VehicleNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VehiclePlateNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VehicleStatusType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsResolved");

                    b.HasIndex("RequestedAt");

                    b.HasIndex("RiderIqamaNo");

                    b.HasIndex("VehicleNumber");

                    b.HasIndex("IsResolved", "VehicleStatusType")
                        .HasFilter("[IsResolved] = 0");

                    b.HasIndex("RiderIqamaNo", "IsResolved");

                    b.ToTable("TempVehicleOperations");
                });

            modelBuilder.Entity("Domain.Entities.Vehicle", b =>
                {
                    b.Property<string>("VehicleNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExstraImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExstraImage1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("LicenseExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("LicenseImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ManufactureYear")
                        .HasColumnType("int");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlateNumberA")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PlateNumberE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SerialNumber")
                        .HasColumnType("int");

                    b.Property<string>("VehicleImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VehicleNumber");

                    b.HasIndex("PlateNumberA");

                    b.HasIndex("SerialNumber");

                    b.HasIndex("VehicleNumber");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("Domain.Entities.Wallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(38, 0)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("MainRiderId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkedRiderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MainRiderId");

                    b.HasIndex("WorkedRiderId");

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "59724D2D-E2B5-4C67-AB6F-D93478347B03",
                            RoleId = "77B96CED-F902-47EF-AE95-ABBE14A8CA22"
                        },
                        new
                        {
                            UserId = "59726D2D-E2B5-4C67-AB6F-D93478317B03",
                            RoleId = "17B96C5D-F502-47TF-EE95-ABVN14A3CA22"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.EmployeeDocuments", b =>
                {
                    b.HasOne("Domain.Entities.Employees", "Employee")
                        .WithOne("EmployeeDocuments")
                        .HasForeignKey("Domain.Entities.EmployeeDocuments", "EmployeeIqamaNo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Domain.Entities.Employees", b =>
                {
                    b.HasOne("Domain.Entities.Housing", "Housing")
                        .WithMany("Employees")
                        .HasForeignKey("HousingId");

                    b.Navigation("Housing");
                });

            modelBuilder.Entity("Domain.Entities.EscapedEmployeeDetails", b =>
                {
                    b.HasOne("Domain.Entities.Employees", "Employee")
                        .WithOne("EscapedDetails")
                        .HasForeignKey("Domain.Entities.EscapedEmployeeDetails", "EmployeeIqamaNo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Domain.Entities.HungerDisability", b =>
                {
                    b.HasOne("Domain.Entities.RiderDetails", "Rider")
                        .WithMany()
                        .HasForeignKey("ActualRiderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Rider");
                });

            modelBuilder.Entity("Domain.Entities.KetaFreeLancer", b =>
                {
                    b.HasOne("Domain.Entities.RiderDetails", "Rider")
                        .WithMany()
                        .HasForeignKey("RiderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rider");
                });

            modelBuilder.Entity("Domain.Entities.RiderDetails", b =>
                {
                    b.HasOne("Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Employees", "Employee")
                        .WithOne("RiderDetails")
                        .HasForeignKey("Domain.Entities.RiderDetails", "EmployeeIqamaNo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Vehicle", "Vehicle")
                        .WithOne("RiderDetails")
                        .HasForeignKey("Domain.Entities.RiderDetails", "VehicleNumber");

                    b.Navigation("Company");

                    b.Navigation("Employee");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Domain.Entities.RiderMonthlyValidity", b =>
                {
                    b.HasOne("Domain.Entities.Employees", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeIqamaNo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Domain.Entities.RiderShift", b =>
                {
                    b.HasOne("Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Housing", "Housing")
                        .WithMany()
                        .HasForeignKey("HousingId");

                    b.HasOne("Domain.Entities.RiderDetails", "Rider")
                        .WithMany("RiderShifts")
                        .HasForeignKey("RiderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Housing");

                    b.Navigation("Rider");
                });

            modelBuilder.Entity("Domain.Entities.RiderShiftSubstitution", b =>
                {
                    b.HasOne("Domain.Entities.RiderDetails", "ActualRider")
                        .WithMany()
                        .HasForeignKey("ActualRiderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.RiderDetails", "SubstituteRider")
                        .WithMany()
                        .HasForeignKey("SubstituteRiderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ActualRider");

                    b.Navigation("SubstituteRider");
                });

            modelBuilder.Entity("Domain.Entities.RiderVehicleStatus", b =>
                {
                    b.HasOne("Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("RiderVehicleStatuses")
                        .HasForeignKey("VehicleNumber")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Domain.Entities.RiderWorkingIdHistory", b =>
                {
                    b.HasOne("Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Employees", "Employee")
                        .WithMany()
                        .HasForeignKey("RiderIqamaNo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Domain.Entities.Spare.Bill", b =>
                {
                    b.HasOne("Domain.Entities.Spare.Supplier", "Supplier")
                        .WithMany("Bills")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Domain.Entities.Spare.BillItem", b =>
                {
                    b.HasOne("Domain.Entities.Spare.Bill", "Bill")
                        .WithMany("BillItems")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("Domain.Entities.Spare.Return", b =>
                {
                    b.HasOne("Domain.Entities.Spare.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Domain.Entities.Spare.ReturnItem", b =>
                {
                    b.HasOne("Domain.Entities.Spare.Return", "Return")
                        .WithMany("ReturnItems")
                        .HasForeignKey("ReturnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Return");
                });

            modelBuilder.Entity("Domain.Entities.Spare.RiderAccessoryUsage", b =>
                {
                    b.HasOne("Domain.Entities.Spare.RiderAccessory", "RiderAccessory")
                        .WithMany("RiderAccessoryUsages")
                        .HasForeignKey("RiderAccessoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.RiderDetails", "Rider")
                        .WithMany()
                        .HasForeignKey("RiderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rider");

                    b.Navigation("RiderAccessory");
                });

            modelBuilder.Entity("Domain.Entities.Spare.SparePartUsage", b =>
                {
                    b.HasOne("Domain.Entities.Spare.SparePart", "SparePart")
                        .WithMany("SparePartUsages")
                        .HasForeignKey("SparePartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleNumber")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SparePart");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Domain.Entities.Spare.TransferItem", b =>
                {
                    b.HasOne("Domain.Entities.Spare.Transfer", "Transfer")
                        .WithMany("TransferItems")
                        .HasForeignKey("TransferId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Transfer");
                });

            modelBuilder.Entity("Domain.Entities.TempEmployeeStatusChange", b =>
                {
                    b.HasOne("Domain.Entities.Employees", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeIqamaNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Domain.Entities.TempEmployeeUpdate", b =>
                {
                    b.HasOne("Domain.Entities.Employees", "Employee")
                        .WithMany()
                        .HasForeignKey("IqamaNo")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Domain.Entities.TempRiderShiftComparison", b =>
                {
                    b.HasOne("Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Housing", "Housing")
                        .WithMany()
                        .HasForeignKey("HousingId");

                    b.HasOne("Domain.Entities.RiderDetails", "Rider")
                        .WithMany()
                        .HasForeignKey("RiderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Housing");

                    b.Navigation("Rider");
                });

            modelBuilder.Entity("Domain.Entities.TempVehicleOperation", b =>
                {
                    b.HasOne("Domain.Entities.RiderDetails", "Rider")
                        .WithMany()
                        .HasForeignKey("RiderIqamaNo")
                        .HasPrincipalKey("EmployeeIqamaNo")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Entities.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rider");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Domain.Entities.Wallet", b =>
                {
                    b.HasOne("Domain.Entities.RiderDetails", "MainRider")
                        .WithMany()
                        .HasForeignKey("MainRiderId");

                    b.HasOne("Domain.Entities.RiderDetails", "WorkedRider")
                        .WithMany()
                        .HasForeignKey("WorkedRiderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MainRider");

                    b.Navigation("WorkedRider");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Domain.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Domain.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Employees", b =>
                {
                    b.Navigation("EmployeeDocuments");

                    b.Navigation("EscapedDetails");

                    b.Navigation("RiderDetails");
                });

            modelBuilder.Entity("Domain.Entities.Housing", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Domain.Entities.RiderDetails", b =>
                {
                    b.Navigation("RiderShifts");
                });

            modelBuilder.Entity("Domain.Entities.Spare.Bill", b =>
                {
                    b.Navigation("BillItems");
                });

            modelBuilder.Entity("Domain.Entities.Spare.Return", b =>
                {
                    b.Navigation("ReturnItems");
                });

            modelBuilder.Entity("Domain.Entities.Spare.RiderAccessory", b =>
                {
                    b.Navigation("RiderAccessoryUsages");
                });

            modelBuilder.Entity("Domain.Entities.Spare.SparePart", b =>
                {
                    b.Navigation("SparePartUsages");
                });

            modelBuilder.Entity("Domain.Entities.Spare.Supplier", b =>
                {
                    b.Navigation("Bills");
                });

            modelBuilder.Entity("Domain.Entities.Spare.Transfer", b =>
                {
                    b.Navigation("TransferItems");
                });

            modelBuilder.Entity("Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("RiderDetails");

                    b.Navigation("RiderVehicleStatuses");
                });
#pragma warning restore 612, 618
        }
    }
}
